name: 🚀 Despliegue para AlwaysData
on:
 push:
  branches:
   - main
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: 📦 Clonar repositorio
     uses: actions/checkout@v4
     
   - name: 🚀 Subir archivos al hosting vía FTPS (AlwaysData)
     uses: SamKirkland/FTP-Deploy-Action@v4.3.5
     with:
        server: ${{ secrets.HOST_DE_FTP }}
        username: ${{ secrets.USUARIO_FTP }}
        password: ${{ secrets.PASS_FTP }}
        server-dir: ${{ secrets.CARPETA_FTP }}
        port: 21
        protocol: ftps
        security: strict    
        local-dir: ./
        exclude: |
            **/.git*
            **/.github*
            **/README.md
            **/node_modules/**
            **/.env